In [2]:
import pandas as pd

In [4]:
# Load the first dataset
df1 = pd.read_parquet('E:\\Stock-Price-Prediction-using-Advanced-modelling\\data\\3_eda\\filtered_OHLCV.parquet')

df2 = pd.read_parquet('E:\\Stock-Price-Prediction-using-Advanced-modelling\\data\\3_eda\\news_sentiment.parquet')

print('Datasets loaded successfully!')

Datasets loaded successfully!

In [5]:
df1

,symbol,date,open,high,low,close,volume,Daily_Return,Overnight_Gap,HL_Range,...,Return_Lag2,Return_Lag3,Volume_Lag1,High_Lag1,Low_Lag1,Consecutive_Up,Day_of_Week,Month,Is_Month_End,target
0,A,2016-01-04,37.824543,37.944297,37.161277,37.483696,3287300,NaN,NaN,0.020890,...,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0.0
1,A,2016-01-05,37.520545,37.723211,37.161277,37.354729,2587200,-0.003441,0.000983,0.015043,...,NaN,NaN,NaN,37.944297,37.161277,0,1,1,0,1.0
2,A,2016-01-06,37.069159,37.760060,36.894129,37.520546,2103600,0.004439,-0.007645,0.023079,...,NaN,NaN,NaN,37.723211,37.161277,1,2,1,0,0.0
3,A,2016-01-07,36.977030,36.986244,35.751834,35.926861,3504300,-0.042475,-0.014486,0.034359,...,-0.003441,NaN,NaN,37.760060,36.894129,0,3,1,0,0.0
4,A,2016-01-08,36.129522,36.580908,35.438621,35.549164,3736700,-0.010513,0.005641,0.032133,...,0.004439,-0.003441,NaN,36.986244,35.751834,0,4,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220273,ZTS,2025-12-24,122.045745,124.613567,122.006086,124.415276,2369000,0.015784,-0.003562,0.020958,...,0.012598,-0.004236,0.780559,122.918214,121.411227,1,2,12,0,1.0
1220274,ZTS,2025-12-26,124.088098,125.238159,123.731180,125.148933,3226800,0.005897,-0.002630,0.012041,...,-0.001939,0.012598,0.384482,124.613567,122.006086,2,4,12,0,0.0
1220275,ZTS,2025-12-29,125.079544,125.763629,124.484676,124.901085,4465600,-0.001980,-0.000554,0.010240,...,0.015784,-0.001939,0.523582,125.238159,123.731180,0,0,12,0,1.0
1220276,ZTS,2025-12-30,124.474765,126.507204,124.375615,125.327400,3230200,0.003413,-0.003413,0.017008,...,0.005897,0.015784,0.711189,125.763629,124.484676,1,1,12,0,0.0
1220277,ZTS,2025-12-31,124.960564,125.753708,124.692872,124.742447,2943300,-0.004667,-0.002927,0.008504,...,-0.001980,0.005897,0.518472,126.507204,124.375615,0,2,12,1,0.0

In [6]:
df2

,ticker,date,News_Count,Daily_Avg_Sentiment,Daily_Sentiment_Std,Positive_Ratio,Negative_Ratio,Neutral_Ratio,Max_Positive,Max_Negative,...,technology,Sentiment_Lag1,Sentiment_Lag2,Sentiment_Lag3,Sentiment_MA3,Sentiment_MA5,Sentiment_Momentum,Sentiment_Trend,NewsCount_Lag1,Neg_Pressure_3d
0,A,2016-01-05,1,0.122718,0.0,0.122718,0.00000,0.877282,0.122718,0.00000,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1,A,2016-02-05,1,-0.638520,0.0,0.000000,0.63852,0.361480,0.000000,0.63852,...,0.833628,0.122718,NaN,NaN,NaN,NaN,NaN,0,1.0,NaN
2,A,2016-02-16,1,0.176532,0.0,0.176532,0.00000,0.823468,0.176532,0.00000,...,0.813530,-0.638520,0.122718,NaN,-0.113090,NaN,0.289622,1,1.0,0.21284
3,A,2016-02-26,1,0.299569,0.0,0.299569,0.00000,0.700431,0.299569,0.00000,...,0.831460,0.176532,-0.638520,0.122718,-0.054140,NaN,0.353709,1,1.0,0.21284
4,A,2016-05-11,1,0.426309,0.0,0.426309,0.00000,0.573691,0.426309,0.00000,...,0.729947,0.299569,0.176532,-0.638520,0.300803,0.077322,0.125506,1,1.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303283,ZTS,2025-12-26,1,0.184648,0.0,0.184648,0.00000,0.815352,0.184648,0.00000,...,0.000000,0.251526,0.375304,0.196234,0.270493,0.264148,-0.085845,0,5.0,0.00000
303284,ZTS,2025-12-27,1,0.299451,0.0,0.299451,0.00000,0.700549,0.299451,0.00000,...,0.000000,0.184648,0.251526,0.375304,0.245208,0.261433,0.054243,1,1.0,0.00000
303285,ZTS,2025-12-29,1,0.104321,0.0,0.104321,0.00000,0.895679,0.104321,0.00000,...,0.000000,0.299451,0.184648,0.251526,0.196140,0.243050,-0.091819,0,1.0,0.00000
303286,ZTS,2025-12-30,1,0.284957,0.0,0.284957,0.00000,0.715043,0.284957,0.00000,...,0.000000,0.104321,0.299451,0.184648,0.229576,0.224981,0.055381,1,1.0,0.00000
303287,ZTS,2025-12-31,1,0.051227,0.0,0.051227,0.00000,0.948773,0.051227,0.00000,...,0.000000,0.284957,0.104321,0.299451,0.146835,0.184921,-0.095608,0,1.0,0.00000

In [11]:
merged_df = pd.merge(df1, df2, how='left', left_on=['symbol', 'date'], right_on=['ticker', 'date'])
merged_df

,symbol,date,open,high,low,close,volume,Daily_Return,Overnight_Gap,HL_Range,...,technology,Sentiment_Lag1,Sentiment_Lag2,Sentiment_Lag3,Sentiment_MA3,Sentiment_MA5,Sentiment_Momentum,Sentiment_Trend,NewsCount_Lag1,Neg_Pressure_3d
0,A,2016-01-04,37.824543,37.944297,37.161277,37.483696,3287300,NaN,NaN,0.020890,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,2016-01-05,37.520545,37.723211,37.161277,37.354729,2587200,-0.003441,0.000983,0.015043,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,A,2016-01-06,37.069159,37.760060,36.894129,37.520546,2103600,0.004439,-0.007645,0.023079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,2016-01-07,36.977030,36.986244,35.751834,35.926861,3504300,-0.042475,-0.014486,0.034359,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,2016-01-08,36.129522,36.580908,35.438621,35.549164,3736700,-0.010513,0.005641,0.032133,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220273,ZTS,2025-12-24,122.045745,124.613567,122.006086,124.415276,2369000,0.015784,-0.003562,0.020958,...,0.607717,0.375304,0.196234,0.313027,0.274355,0.283960,-0.022829,0.0,1.0,0.0
1220274,ZTS,2025-12-26,124.088098,125.238159,123.731180,125.148933,3226800,0.005897,-0.002630,0.012041,...,0.000000,0.251526,0.375304,0.196234,0.270493,0.264148,-0.085845,0.0,5.0,0.0
1220275,ZTS,2025-12-29,125.079544,125.763629,124.484676,124.901085,4465600,-0.001980,-0.000554,0.010240,...,0.000000,0.299451,0.184648,0.251526,0.196140,0.243050,-0.091819,0.0,1.0,0.0
1220276,ZTS,2025-12-30,124.474765,126.507204,124.375615,125.327400,3230200,0.003413,-0.003413,0.017008,...,0.000000,0.104321,0.299451,0.184648,0.229576,0.224981,0.055381,1.0,1.0,0.0
1220277,ZTS,2025-12-31,124.960564,125.753708,124.692872,124.742447,2943300,-0.004667,-0.002927,0.008504,...,0.000000,0.284957,0.104321,0.299451,0.146835,0.184921,-0.095608,0.0,1.0,0.0

In [12]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1220278 entries, 0 to 1220277
Data columns (total 93 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   symbol                    1220278 non-null  str
 1   date                      1220278 non-null  datetime64[ms]
 2   open                      1220278 non-null  float64
 3   high                      1220278 non-null  float64
 4   low                       1220278 non-null  float64
 5   close                     1220278 non-null  float64
 6   volume                    1220278 non-null  int64
 7   Daily_Return              1219778 non-null  float64
 8   Overnight_Gap             1219778 non-null  float64
 9   HL_Range                  1220278 non-null  float64
 10  CO_Spread                 1220278 non-null  float64
 11  Upper_Shadow              1220278 non-null  float64
 12  Lower_Shadow              1220278 non-null  float64
 13  Body_Size                 1220278 non-null  float64
 14  SMA_5                     1218278 non-null  float64
 15  SMA_10                    1215778 non-null  float64
 16  SMA_20                    1210778 non-null  float64
 17  SMA_50                    1195781 non-null  float64
 18  EMA_12                    1214778 non-null  float64
 19  EMA_26                    1207778 non-null  float64
 20  Price_vs_SMA20            1210778 non-null  float64
 21  SMA5_vs_SMA20             1210778 non-null  float64
 22  EMA_Cross                 1207778 non-null  float64
 23  RSI_14                    1213778 non-null  float64
 24  MACD                      1207778 non-null  float64
 25  MACD_Signal               1203778 non-null  float64
 26  MACD_Hist                 1203778 non-null  float64
 27  Stoch_K                   1213547 non-null  float64
 28  Stoch_D                   1212497 non-null  float64
 29  ROC_5                     1217778 non-null  float64
 30  ROC_10                    1215278 non-null  float64
 31  Williams_R                1213547 non-null  float64
 32  CCI_20                    1210649 non-null  float64
 33  ADX_14                    1220278 non-null  float64
 34  ATR_14                    1220278 non-null  float64
 35  BB_Upper                  1210778 non-null  float64
 36  BB_Lower                  1210778 non-null  float64
 37  BB_Mid                    1210778 non-null  float64
 38  BB_Width                  1210778 non-null  float64
 39  BB_Position               1210778 non-null  float64
 40  Rolling_Std_5             1217778 non-null  float64
 41  Rolling_Std_20            1210278 non-null  float64
 42  Volatility_Ratio          1210278 non-null  float64
 43  Volume_MA_Ratio           1210778 non-null  float64
 44  OBV                       1220278 non-null  int64
 45  OBV_Signal                1220278 non-null  float64
 46  Volume_Spike              1220278 non-null  int64
 47  VWAP                      1210671 non-null  float64
 48  Price_vs_VWAP             1210671 non-null  float64
 49  Volume_Return_Corr        1212042 non-null  float64
 50  Return_Lag1               1219278 non-null  float64
 51  Return_Lag2               1218778 non-null  float64
 52  Return_Lag3               1218278 non-null  float64
 53  Volume_Lag1               1210278 non-null  float64
 54  High_Lag1                 1219778 non-null  float64
 55  Low_Lag1                  1219778 non-null  float64
 56  Consecutive_Up            1220278 non-null  int64
 57  Day_of_Week               1220278 non-null  int32
 58  Month                     1220278 non-null  int32
 59  Is_Month_End              1220278 non-null  int64
 60  target                    1220278 non-null  float64
 61  ticker                    277797 non-null   str
 62  News_Count                277797 non-null   float64
 63  Daily_Avg_Sentiment       277797 non-null   float64
 64  Daily_Sentiment_Std       277797 non-null   float64
 65  Positive_Ratio            277797 non-null   float64
 66  Negative_Ratio            277797 non-null   float64
 67  Neutral_Ratio             277797 non-null   float64
 68  Max_Positive              277797 non-null   float64
 69  Max_Negative              277797 non-null   float64
 70  Sentiment_Range           277797 non-null   float64
 71  Dominant_Sentiment_Label  277797 non-null   str
 72  Avg_Ticker_Relevance      277797 non-null   float64
 73  Avg_Ticker_Sentiment      277797 non-null   float64
 74  earnings                  277797 non-null   float64
 75  economy_macro             277797 non-null   float64
 76  energy_transportation     277797 non-null   float64
 77  finance                   277797 non-null   float64
 78  financial_markets         277797 non-null   float64
 79  life_sciences             277797 non-null   float64
 80  manufacturing             277797 non-null   float64
 81  mergers_and_acquisitions  277797 non-null   float64
 82  retail_wholesale          277797 non-null   float64
 83  technology                277797 non-null   float64
 84  Sentiment_Lag1            277360 non-null   float64
 85  Sentiment_Lag2            276920 non-null   float64
 86  Sentiment_Lag3            276482 non-null   float64
 87  Sentiment_MA3             276920 non-null   float64
 88  Sentiment_MA5             276049 non-null   float64
 89  Sentiment_Momentum        276920 non-null   float64
 90  Sentiment_Trend           277797 non-null   float64
 91  NewsCount_Lag1            277360 non-null   float64
 92  Neg_Pressure_3d           276920 non-null   float64
dtypes: datetime64[ms](1), float64(82), int32(2), int64(5), str(3)
memory usage: 864.2 MB

In [13]:
merged_df.shape

(1220278, 93)

In [15]:
merged_df.isnull().sum().max()

np.int64(944229)